# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    apply_arithmetic_operation_over_rows as apply_arithmetic_operation_over_rows,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_apn.tasks import (
    add_fullscreen_to_map as add_fullscreen_to_map,
)
from ecoscope_workflows_ext_apn.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_apn.tasks import (
    collect_optional_layers as collect_optional_layers,
)
from ecoscope_workflows_ext_apn.tasks import consolidate_cols as consolidate_cols
from ecoscope_workflows_ext_apn.tasks import (
    draw_bar_chart_colored as draw_bar_chart_colored,
)
from ecoscope_workflows_ext_apn.tasks import draw_doughnut_chart as draw_doughnut_chart
from ecoscope_workflows_ext_apn.tasks import (
    draw_time_series_line_chart_grouped as draw_time_series_line_chart_grouped,
)
from ecoscope_workflows_ext_apn.tasks import (
    explode_json_array_column as explode_json_array_column,
)
from ecoscope_workflows_ext_apn.tasks import (
    extract_array_length_from_json_column as extract_array_length_from_json_column,
)
from ecoscope_workflows_ext_apn.tasks import fill_numeric_nulls as fill_numeric_nulls
from ecoscope_workflows_ext_apn.tasks import filter_numeric_gt as filter_numeric_gt
from ecoscope_workflows_ext_apn.tasks import (
    gather_apn_dashboard as gather_apn_dashboard,
)
from ecoscope_workflows_ext_apn.tasks import (
    generate_stat_cards_html as generate_stat_cards_html,
)
from ecoscope_workflows_ext_apn.tasks import get_time_interval as get_time_interval
from ecoscope_workflows_ext_apn.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_apn.tasks import (
    preserve_table_headers as preserve_table_headers,
)
from ecoscope_workflows_ext_apn.tasks import set_color_palette as set_color_palette
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    user_details = (
        task(get_user_me)
        .validate()
        .set_task_instance_id("user_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("user_details") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    locale = (
        task(set_locale)
        .validate()
        .set_task_instance_id("locale")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(locale_str="es_ES", **(params.get("locale") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    plot_palette = (
        task(set_color_palette)
        .validate()
        .set_task_instance_id("plot_palette")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("plot_palette") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    events = (
        task(get_events)
        .validate()
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "serial_number",
                "state",
                "geometry",
                "event_details",
            ],
            event_types=["amenazas_funcionario", "animal_exotico"],
            include_details=True,
            raise_on_empty=False,
            include_updates=False,
            include_display_values=True,
            include_related_events=False,
            include_null_geometry=True,
            **(params.get("events") or {}),
        )
        .call()
    )

    events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("events_tz") or {}),
        )
        .call()
    )

    processed_events = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("processed_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_tz,
            client=er_client,
            map_to_titles=False,
            ordered=True,
            **(params.get("processed_events") or {}),
        )
        .call()
    )

    processed_agresion = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("processed_agresion")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_events,
            column="event_type",
            values=["amenazas_funcionario"],
            **(params.get("processed_agresion") or {}),
        )
        .call()
    )

    processed_exotica = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("processed_exotica")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_events,
            column="event_type",
            values=["animal_exotico"],
            **(params.get("processed_exotica") or {}),
        )
        .call()
    )

    uso_arma_count = (
        task(extract_array_length_from_json_column)
        .validate()
        .set_task_instance_id("uso_arma_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_events,
            column_name="event_details",
            field_name="uso_arma",
            output_column_name="uso_arma_count",
            **(params.get("uso_arma_count") or {}),
        )
        .call()
    )

    weapon_events = (
        task(filter_numeric_gt)
        .validate()
        .set_task_instance_id("weapon_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=uso_arma_count,
            column_name="uso_arma_count",
            value=0.0,
            reset_index=True,
            **(params.get("weapon_events") or {}),
        )
        .call()
    )

    weapon_exotica = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("weapon_exotica")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=weapon_events,
            column="event_type",
            values=["animal_exotico"],
            **(params.get("weapon_exotica") or {}),
        )
        .call()
    )

    exploded_weapon_uses = (
        task(explode_json_array_column)
        .validate()
        .set_task_instance_id("exploded_weapon_uses")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=weapon_events,
            json_column="event_details",
            array_field="uso_arma",
            parent_columns=[
                "time",
                "serial_number",
                "event_type",
                "event_type_display",
            ],
            **(params.get("exploded_weapon_uses") or {}),
        )
        .call()
    )

    all_weapon_uses = (
        task(consolidate_cols)
        .validate()
        .set_task_instance_id("all_weapon_uses")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exploded_weapon_uses,
            source_columns=["tirador", "nombre_tirador"],
            output_column="tirador_name",
            drop_sources=True,
            **(params.get("all_weapon_uses") or {}),
        )
        .call()
    )

    total_incidents = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_incidents")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=weapon_events, **(params.get("total_incidents") or {}))
        .call()
    )

    total_incidents_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_incidents_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Incidentes con uso de armamento",
            decimal_places=0,
            data=total_incidents,
            **(params.get("total_incidents_sv") or {}),
        )
        .call()
    )

    total_ammo = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_ammo")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            column_name="cantidad_municiones",
            **(params.get("total_ammo") or {}),
        )
        .call()
    )

    total_ammo_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_ammo_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total de municiones utilizadas",
            decimal_places=0,
            data=total_ammo,
            **(params.get("total_ammo_sv") or {}),
        )
        .call()
    )

    total_personnel = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_personnel")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            column_name="tirador_name",
            **(params.get("total_personnel") or {}),
        )
        .call()
    )

    total_personnel_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_personnel_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Personal que efectuó disparos",
            decimal_places=0,
            data=total_personnel,
            **(params.get("total_personnel_sv") or {}),
        )
        .call()
    )

    abatidos_per_event = (
        task(extract_array_length_from_json_column)
        .validate()
        .set_task_instance_id("abatidos_per_event")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=weapon_exotica,
            column_name="event_details",
            field_name="abatidos",
            output_column_name="abatidos_count",
            **(params.get("abatidos_per_event") or {}),
        )
        .call()
    )

    total_abatidos = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_abatidos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=abatidos_per_event,
            column_name="abatidos_count",
            **(params.get("total_abatidos") or {}),
        )
        .call()
    )

    total_abatidos_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_abatidos_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Animales abatidos (Exótica)",
            decimal_places=0,
            data=total_abatidos,
            **(params.get("total_abatidos_sv") or {}),
        )
        .call()
    )

    spatial_features = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            tooltip_columns=[],
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    local_spatial_file = (
        task(load_local_spatial_file)
        .validate()
        .set_task_instance_id("local_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("local_spatial_file") or {}))
        .call()
    )

    local_spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("local_spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=local_spatial_file,
            tooltip_columns=[],
            **(params.get("local_spatial_features_layer") or {}),
        )
        .call()
    )

    weapon_events_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("weapon_events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=weapon_events, **(params.get("weapon_events_colormap") or {}))
        .call()
    )

    weapon_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("weapon_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("weapon_legend_title") or {}))
        .call()
    )

    weapon_map_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("weapon_map_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=weapon_events_colormap,
            legend={
                "title": weapon_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            tooltip_columns=[
                "serial_number",
                "event_type_display",
                "time",
                "reported_by",
            ],
            **(params.get("weapon_map_layer") or {}),
        )
        .call()
    )

    optional_geo_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("optional_geo_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[
                spatial_features_layer,
                local_spatial_features_layer,
                weapon_map_layer,
            ],
            **(params.get("optional_geo_layers") or {}),
        )
        .call()
    )

    weapon_map_view_state = (
        task(view_state_from_layers)
        .validate()
        .set_task_instance_id("weapon_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[weapon_map_layer],
            max_zoom=20,
            **(params.get("weapon_map_view_state") or {}),
        )
        .call()
    )

    weapon_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("weapon_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=optional_geo_layers,
            tile_layers=base_maps,
            view_state=weapon_map_view_state,
            static=False,
            title=None,
            output_type="html",
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            **(params.get("weapon_map") or {}),
        )
        .call()
    )

    weapon_map_fullscreen = (
        task(add_fullscreen_to_map)
        .validate()
        .set_task_instance_id("weapon_map_fullscreen")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(html=weapon_map, **(params.get("weapon_map_fullscreen") or {}))
        .call()
    )

    weapon_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("weapon_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=weapon_map_fullscreen,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="weapon_map",
            **(params.get("weapon_map_html") or {}),
        )
        .call()
    )

    weapon_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("weapon_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa de incidentes",
            data=weapon_map_html,
            **(params.get("weapon_map_widget") or {}),
        )
        .call()
    )

    time_interval_config = (
        task(get_time_interval)
        .validate()
        .set_task_instance_id("time_interval_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_interval_config") or {}))
        .call()
    )

    incidents_trend_chart = (
        task(draw_time_series_line_chart_grouped)
        .validate()
        .set_task_instance_id("incidents_trend_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=weapon_events,
            x_axis="time",
            y_axis="serial_number",
            category="event_type_display",
            agg_function="count",
            time_interval=time_interval_config,
            color_palette=plot_palette,
            layout_style={
                "showlegend": True,
                "legend_title": "Tipo de evento",
                "hovermode": "x unified",
                "xaxis": {"title": "Período"},
                "yaxis": {"title": "Nro. de incidentes"},
            },
            **(params.get("incidents_trend_chart") or {}),
        )
        .call()
    )

    incidents_trend_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("incidents_trend_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=incidents_trend_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_trend",
            **(params.get("incidents_trend_html") or {}),
        )
        .call()
    )

    incidents_trend_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("incidents_trend_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Uso de armamento por mes",
            data=incidents_trend_html,
            **(params.get("incidents_trend_sv") or {}),
        )
        .call()
    )

    ammo_trend_chart = (
        task(draw_time_series_line_chart_grouped)
        .validate()
        .set_task_instance_id("ammo_trend_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=all_weapon_uses,
            x_axis="time",
            y_axis="cantidad_municiones",
            category="event_type_display",
            agg_function="sum",
            time_interval=time_interval_config,
            color_palette=plot_palette,
            layout_style={
                "showlegend": True,
                "legend_title": "Tipo de evento",
                "hovermode": "x unified",
                "xaxis": {"title": "Período"},
                "yaxis": {"title": "Cantidad de municiones"},
            },
            **(params.get("ammo_trend_chart") or {}),
        )
        .call()
    )

    ammo_trend_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ammo_trend_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=ammo_trend_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ammo_trend",
            **(params.get("ammo_trend_html") or {}),
        )
        .call()
    )

    ammo_trend_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("ammo_trend_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Uso de municiones por mes",
            data=ammo_trend_html,
            **(params.get("ammo_trend_sv") or {}),
        )
        .call()
    )

    ammo_by_type = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("ammo_by_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            groupby_cols=["tipo_municion"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Cantidad de eventos",
                    "aggregator": "count",
                    "column": "serial_number",
                    "decimal_places": 0,
                },
                {
                    "display_name": "Total municiones",
                    "aggregator": "sum",
                    "column": "cantidad_municiones",
                    "decimal_places": 0,
                },
            ],
            **(params.get("ammo_by_type") or {}),
        )
        .call()
    )

    ammo_table_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("ammo_table_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=ammo_by_type,
            raise_if_not_found=False,
            retain_columns=None,
            drop_columns=None,
            rename_columns={"tipo_municion": "Tipo de munición"},
            duplicate_strategy="suffix",
            **(params.get("ammo_table_columns") or {}),
        )
        .call()
    )

    ammo_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("ammo_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dataframe=ammo_table_columns, **(params.get("ammo_table") or {}))
        .call()
    )

    ammo_table_fixed = (
        task(preserve_table_headers)
        .validate()
        .set_task_instance_id("ammo_table_fixed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(html=ammo_table, **(params.get("ammo_table_fixed") or {}))
        .call()
    )

    ammo_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ammo_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=ammo_table_fixed,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ammo_table",
            **(params.get("ammo_table_html") or {}),
        )
        .call()
    )

    ammo_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("ammo_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Uso de munición por tipo",
            data=ammo_table_html,
            **(params.get("ammo_table_sv") or {}),
        )
        .call()
    )

    agresion_weapon_uses = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("agresion_weapon_uses")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            column="event_type",
            values=["amenazas_funcionario"],
            **(params.get("agresion_weapon_uses") or {}),
        )
        .call()
    )

    exotica_weapon_uses = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("exotica_weapon_uses")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            column="event_type",
            values=["animal_exotico"],
            **(params.get("exotica_weapon_uses") or {}),
        )
        .call()
    )

    agresion_per_tirador = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("agresion_per_tirador")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=agresion_weapon_uses,
            groupby_cols=["tirador_name"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Agresiones",
                    "aggregator": "nunique",
                    "column": "serial_number",
                    "decimal_places": 0,
                }
            ],
            **(params.get("agresion_per_tirador") or {}),
        )
        .call()
    )

    exotica_per_tirador = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("exotica_per_tirador")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exotica_weapon_uses,
            groupby_cols=["tirador_name"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Exóticos",
                    "aggregator": "nunique",
                    "column": "serial_number",
                    "decimal_places": 0,
                }
            ],
            **(params.get("exotica_per_tirador") or {}),
        )
        .call()
    )

    ammo_per_tirador = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("ammo_per_tirador")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_weapon_uses,
            groupby_cols=["tirador_name"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Total municiones",
                    "aggregator": "sum",
                    "column": "cantidad_municiones",
                    "decimal_places": 0,
                }
            ],
            **(params.get("ammo_per_tirador") or {}),
        )
        .call()
    )

    personnel_merge1 = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("personnel_merge1")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=agresion_per_tirador,
            right=exotica_per_tirador,
            on="tirador_name",
            how="outer",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("personnel_merge1") or {}),
        )
        .call()
    )

    personnel_merge2 = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("personnel_merge2")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=personnel_merge1,
            right=ammo_per_tirador,
            on="tirador_name",
            how="outer",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("personnel_merge2") or {}),
        )
        .call()
    )

    personnel_filled = (
        task(fill_numeric_nulls)
        .validate()
        .set_task_instance_id("personnel_filled")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=personnel_merge2,
            columns=["Agresiones", "Exóticos", "Total municiones"],
            value=0.0,
            **(params.get("personnel_filled") or {}),
        )
        .call()
    )

    personnel_total = (
        task(apply_arithmetic_operation_over_rows)
        .validate()
        .set_task_instance_id("personnel_total")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=personnel_filled,
            column_a="Agresiones",
            column_b="Exóticos",
            output_column="Total",
            operation="add",
            **(params.get("personnel_total") or {}),
        )
        .call()
    )

    personnel_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("personnel_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=personnel_total,
            raise_if_not_found=False,
            retain_columns=[
                "tirador_name",
                "Agresiones",
                "Exóticos",
                "Total",
                "Total municiones",
            ],
            drop_columns=None,
            rename_columns={"tirador_name": "Tirador"},
            duplicate_strategy="suffix",
            **(params.get("personnel_columns") or {}),
        )
        .call()
    )

    personnel_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("personnel_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dataframe=personnel_columns, **(params.get("personnel_table") or {}))
        .call()
    )

    personnel_table_fixed = (
        task(preserve_table_headers)
        .validate()
        .set_task_instance_id("personnel_table_fixed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(html=personnel_table, **(params.get("personnel_table_fixed") or {}))
        .call()
    )

    personnel_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("personnel_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=personnel_table_fixed,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="personnel_table",
            **(params.get("personnel_table_html") or {}),
        )
        .call()
    )

    personnel_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("personnel_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Actividad del personal",
            data=personnel_table_html,
            **(params.get("personnel_table_sv") or {}),
        )
        .call()
    )

    extract_desfundar = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_desfundar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_agresion,
            column_name="event_details",
            field_name_options=["necesidad_desfundar"],
            output_column_name="necesidad_desfundar",
            output_type="str",
            fan_out=True,
            **(params.get("extract_desfundar") or {}),
        )
        .call()
    )

    filter_desfundar = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_desfundar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_desfundar,
            column="necesidad_desfundar",
            values=["Sí", "yes", "si", "Si"],
            **(params.get("filter_desfundar") or {}),
        )
        .call()
    )

    count_desfundar = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("count_desfundar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=filter_desfundar, **(params.get("count_desfundar") or {}))
        .call()
    )

    count_desfundar_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("count_desfundar_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Necesidad de desfundar el arma",
            decimal_places=0,
            data=count_desfundar,
            **(params.get("count_desfundar_sv") or {}),
        )
        .call()
    )

    extract_lesion_desc = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_lesion_desc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_agresion,
            column_name="event_details",
            field_name_options=["descripcion_lesiones"],
            output_column_name="descripcion_lesiones",
            output_type="str",
            fan_out=True,
            **(params.get("extract_lesion_desc") or {}),
        )
        .call()
    )

    lesiones_count = (
        task(extract_array_length_from_json_column)
        .validate()
        .set_task_instance_id("lesiones_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_lesion_desc,
            column_name="event_details",
            field_name="lesiones_sufridas",
            output_column_name="lesiones_count",
            **(params.get("lesiones_count") or {}),
        )
        .call()
    )

    events_with_lesiones = (
        task(filter_numeric_gt)
        .validate()
        .set_task_instance_id("events_with_lesiones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=lesiones_count,
            column_name="lesiones_count",
            value=0.0,
            reset_index=True,
            **(params.get("events_with_lesiones") or {}),
        )
        .call()
    )

    exploded_lesiones = (
        task(explode_json_array_column)
        .validate()
        .set_task_instance_id("exploded_lesiones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lesiones,
            json_column="event_details",
            array_field="lesiones_sufridas",
            parent_columns=["time", "serial_number", "descripcion_lesiones"],
            **(params.get("exploded_lesiones") or {}),
        )
        .call()
    )

    lesiones_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("lesiones_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exploded_lesiones,
            raise_if_not_found=False,
            retain_columns=["time", "lesiones_sufridas", "descripcion_lesiones"],
            drop_columns=None,
            rename_columns={
                "time": "Fecha y hora",
                "lesiones_sufridas": "Tipo de lesión",
                "descripcion_lesiones": "Descripción",
            },
            duplicate_strategy="suffix",
            **(params.get("lesiones_columns") or {}),
        )
        .call()
    )

    lesiones_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("lesiones_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dataframe=lesiones_columns, **(params.get("lesiones_table") or {}))
        .call()
    )

    lesiones_table_fixed = (
        task(preserve_table_headers)
        .validate()
        .set_task_instance_id("lesiones_table_fixed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(html=lesiones_table, **(params.get("lesiones_table_fixed") or {}))
        .call()
    )

    lesiones_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("lesiones_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=lesiones_table_fixed,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="lesiones_table",
            **(params.get("lesiones_table_html") or {}),
        )
        .call()
    )

    lesiones_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("lesiones_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Lesiones sufridas",
            data=lesiones_table_html,
            **(params.get("lesiones_table_sv") or {}),
        )
        .call()
    )

    exploded_accion = (
        task(explode_json_array_column)
        .validate()
        .set_task_instance_id("exploded_accion")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=weapon_exotica,
            json_column="event_details",
            array_field="accion_control",
            parent_columns=["serial_number"],
            **(params.get("exploded_accion") or {}),
        )
        .call()
    )

    accion_counts = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("accion_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exploded_accion,
            groupby_cols=["accion_control"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Cantidad",
                    "aggregator": "count",
                    "column": "serial_number",
                    "decimal_places": 0,
                }
            ],
            **(params.get("accion_counts") or {}),
        )
        .call()
    )

    accion_doughnut = (
        task(draw_doughnut_chart)
        .validate()
        .set_task_instance_id("accion_doughnut")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=accion_counts,
            value_column="Cantidad",
            label_column="accion_control",
            color_palette=plot_palette,
            hole=0.5,
            layout_style=None,
            **(params.get("accion_doughnut") or {}),
        )
        .call()
    )

    accion_doughnut_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("accion_doughnut_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=accion_doughnut,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="accion_doughnut",
            **(params.get("accion_doughnut_html") or {}),
        )
        .call()
    )

    accion_doughnut_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("accion_doughnut_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Resultado de acción de control",
            data=accion_doughnut_html,
            **(params.get("accion_doughnut_sv") or {}),
        )
        .call()
    )

    extract_especie = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_especie")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=abatidos_per_event,
            column_name="event_details",
            field_name_options=["especie_exotica"],
            output_column_name="especie_exotica",
            output_type="str",
            fan_out=True,
            **(params.get("extract_especie") or {}),
        )
        .call()
    )

    filter_abatidos = (
        task(filter_numeric_gt)
        .validate()
        .set_task_instance_id("filter_abatidos")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_especie,
            column_name="abatidos_count",
            value=0.0,
            reset_index=True,
            **(params.get("filter_abatidos") or {}),
        )
        .call()
    )

    species_killed = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("species_killed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_abatidos,
            groupby_cols=["especie_exotica"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Animales abatidos",
                    "aggregator": "sum",
                    "column": "abatidos_count",
                    "decimal_places": 0,
                }
            ],
            **(params.get("species_killed") or {}),
        )
        .call()
    )

    species_chart = (
        task(draw_bar_chart_colored)
        .validate()
        .set_task_instance_id("species_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=species_killed,
            x_axis="especie_exotica",
            y_axis="Animales abatidos",
            color_palette=plot_palette,
            text_template="%{y:.0f}",
            layout_style={
                "showlegend": False,
                "hovermode": "x",
                "xaxis": {"title": "Especie"},
                "yaxis": {"title": "Cantidad abatida"},
                "bargap": 0.2,
            },
            **(params.get("species_chart") or {}),
        )
        .call()
    )

    species_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("species_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=species_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="species_chart",
            **(params.get("species_chart_html") or {}),
        )
        .call()
    )

    species_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("species_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Animales abatidos por especie",
            data=species_chart_html,
            **(params.get("species_chart_sv") or {}),
        )
        .call()
    )

    stat_cards_html = (
        task(generate_stat_cards_html)
        .validate()
        .set_task_instance_id("stat_cards_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=[
                total_incidents_sv,
                total_ammo_sv,
                total_personnel_sv,
                total_abatidos_sv,
                count_desfundar_sv,
            ],
            **(params.get("stat_cards_html") or {}),
        )
        .call()
    )

    stat_cards_html_file = (
        task(persist_text)
        .validate()
        .set_task_instance_id("stat_cards_html_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            text=stat_cards_html,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="stat_cards",
            **(params.get("stat_cards_html_file") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_apn_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_incidents_sv,
                total_ammo_sv,
                total_personnel_sv,
                total_abatidos_sv,
                weapon_map_widget,
                incidents_trend_sv,
                ammo_trend_sv,
                ammo_table_sv,
                personnel_table_sv,
                count_desfundar_sv,
                lesiones_table_sv,
                accion_doughnut_sv,
                species_chart_sv,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
